/** Bilingual Urdu / English copy for labels (forms, tables, sidebar). Default UI is Urdu. */
export const FL = {
  // Sidebar groups
  groupOverview: { ur: 'جائزہ', en: 'Overview' },
  groupPeople: { ur: 'طلباء و اساتذہ', en: 'People & classes' },
  groupOperations: { ur: 'روزمرہ کارروائیاں', en: 'Daily operations' },
  groupFinance: { ur: 'مالیات و اثاثے', en: 'Finance & stock' },
  groupSystem: { ur: 'سسٹم', en: 'System' },
  navTartibat: { ur: 'ترتیبات', en: 'Tartibat' },

  settingsAddressBlock: { ur: 'ادارے کا پتہ', en: 'Organization address' },
  institutionLogo: { ur: 'ادارے کا لوگو', en: 'Institution logo' },
  institutionNameUr: { ur: 'مدرسہ / ادارے کا نام', en: 'Madrasa / institution name' },
  institutionNameEn: { ur: 'مدرسہ / ادارے کا نام — انگریزی', en: 'Institution name (English)' },
  institutionLogoHint: {
    ur: 'یہ لوگو ہیڈر، پرنٹ اور کارڈز میں دکھایا جائے گا۔',
    en: 'Shown in the header, prints, and result cards.',
  },
  settingsBooksBlock: { ur: 'کتب', en: 'Books' },
  collegeAffiliationSection: { ur: 'جامعہ وابستگی', en: 'College affiliation' },
  basicTartibatSection: { ur: 'بنیادی ترتیبات', en: 'Basic settings' },
  tartibatTileCountries: { ur: 'ممالک', en: 'Countries' },
  tartibatTileGuardianRelations: { ur: 'رشتے (سرپرست)', en: 'Guardian relations' },
  tartibatTileAddresses: { ur: 'تمام ایڈریس', en: 'All addresses' },
  tartibatTilePreviousMadaris: { ur: 'سابقہ مدارس کے نام', en: 'Previous madaris names' },
  tartibatTileBooks: { ur: 'پڑھائی جانے والی کتابیں', en: 'Books being taught' },
  tartibatTileExamNames: { ur: 'امتحان کے نام', en: 'Exam names' },
  tartibatTileLessonNames: { ur: 'اسباق / دروس', en: 'Lessons / syllabus' },
  tartibatTileGrades: { ur: 'پڑھائے جانے والے درجات', en: 'Classes / grades' },
  tartibatTileAttendanceTimes: { ur: 'حاضری کے اوقات', en: 'Attendance periods' },
  tartibatTileWithdrawal: { ur: 'اخراج کی وجوہات', en: 'Withdrawal reasons' },
  tartibatTabAddress: { ur: 'ایڈریس', en: 'Addresses' },
  tartibatTabDistricts: { ur: 'اضلاع', en: 'Districts' },
  tartibatPeriodName: { ur: 'وقت / پیریئڈ کا نام', en: 'Period name' },
  withdrawalMarksYearComplete: { ur: 'کلاس/سال مکمل؟', en: 'Class/year completed?' },
  tartibatExistingList: { ur: 'موجودہ اندراج', en: 'Saved entries' },
  addressInfoSection: { ur: 'پتے کی معلومات', en: 'Address information' },

  // Sidebar items (nav)
  navDashboard: { ur: 'ڈیش بورڈ', en: 'Dashboard' },
  navStudents: { ur: 'طلباء', en: 'Students' },
  navIdCards: { ur: 'شناختی کارڈز', en: 'Student ID Cards' },
  navIdCardsHub: { ur: 'جنریٹ / پرنٹ', en: 'Generate / Print' },
  navIdCardsPrint: { ur: 'پرنٹ پریویو', en: 'Print preview' },
  navIdCardsTemplates: { ur: 'ٹیمپلیٹس', en: 'Templates' },
  navIdCardsHistory: { ur: 'پرنٹ ہسٹری', en: 'Print history' },
  navTeachers: { ur: 'اساتذہ', en: 'Teachers' },
  navGrades: { ur: 'درجات', en: 'Grades' },
  navAttendance: { ur: 'حاضری', en: 'Attendance' },
  navStudentCharacter: { ur: 'طلباء کا اخلاق', en: 'Student character' },
  navExams: { ur: 'امتحانات', en: 'Examinations' },
  navFees: { ur: 'فیس', en: 'Fees' },
  navFinance: { ur: 'آمد و خرچ', en: 'Income & expense' },
  navInventory: { ur: 'انوینٹری', en: 'Inventory' },
  navLibrary: { ur: 'لائبریری', en: 'Library' },
  navSpeeches: { ur: 'تقریریں / خلاصہ', en: 'Speeches' },
  navSettings: { ur: 'ترقیات / ترتیبات', en: 'Settings' },
  navProfile: { ur: 'پروفائل', en: 'Profile' },
  navTartibat: { ur: 'ترتیبات', en: 'Tartibat' },
  navTartibatSessions: { ur: 'سیشن', en: 'Sessions' },
  navTartibatSubjects: { ur: 'شعبہ جات', en: 'Subajat' },
  navTartibatDarajat: { ur: 'درجات (کلاس)', en: 'Darajat (classes)' },
  navTartibatBooks: { ur: 'کتب', en: 'Books' },
  navBookReading: { ur: 'کتاب مطالعہ', en: 'Book Reading' },
  navTartibatTimetable: { ur: 'ٹائم ٹیبل', en: 'Timetable' },

  hashSerial: { ur: '#', en: '#' },
  salaryBasic: { ur: 'بنیادی تنخواہ', en: 'Basic salary' },
  salaryTotalGross: { ur: 'کل تنخواہ', en: 'Total salary' },
  salaryDeduction: { ur: 'کٹوتی', en: 'Deduction' },
  salaryNet: { ur: 'خالص تنخواہ', en: 'Net salary' },
  salaryFrom: { ur: 'از تاریخ', en: 'From date' },
  salaryTo: { ur: 'تا تاریخ', en: 'To date' },
  salaryStatusLabel: { ur: 'حالت', en: 'Status' },
  salaryInvoice: { ur: 'رسید', en: 'Invoice' },
  salaryPayment: { ur: 'ادائیگی', en: 'Payment' },
  districtCurrentLabel: { ur: 'موجودہ ضلع / شہر', en: 'District / city' },

  // Login
  authTenant: { ur: 'ادارہ / ٹیننٹ', en: 'Organization' },
  /** URL-safe code for the organization (tenant), unique across the system */
  authOrgSlug: { ur: 'ادارے کا کوڈ (یونیک)', en: 'Organization code' },
  authUsername: { ur: 'صارف نام', en: 'Username' },
  authPassword: { ur: 'پاس ورڈ', en: 'Password' },
  authConfirmPassword: { ur: 'پاس ورڈ کی تصدیق', en: 'Confirm password' },

  // Common actions
  search: { ur: 'تلاش', en: 'Search' },
  filter: { ur: 'فلٹر', en: 'Filter' },
  print: { ur: 'پرنٹ', en: 'Print' },
  add: { ur: 'نیا اندراج', en: 'Add new' },
  edit: { ur: 'ترمیم', en: 'Edit' },
  delete: { ur: 'حذف', en: 'Delete' },
  actions: { ur: 'اعمال', en: 'Actions' },
  save: { ur: 'محفوظ کریں', en: 'Save' },
  cancel: { ur: 'منسوخ', en: 'Cancel' },

  // Students table & form
  studentId: { ur: 'طالب علم آئی ڈی', en: 'Student ID' },
  fullName: { ur: 'نام', en: 'Full name' },
  nameUrField: { ur: 'نام — اردو میں', en: 'Name (Urdu script)' },
  nameEnField: { ur: 'نام — انگریزی میں', en: 'Name (English)' },
  fatherName: { ur: 'والد کا نام', en: "Father's name" },
  fatherUr: { ur: 'والد — اردو', en: 'Father (Urdu)' },
  fatherEn: { ur: 'والد — انگریزی', en: 'Father (English)' },
  phone: { ur: 'فون نمبر', en: 'Phone' },
  city: { ur: 'شہر', en: 'City' },
  state: { ur: 'صوبہ / ریاست', en: 'State / province' },
  classGrade: { ur: 'کلاس / درجہ', en: 'Class / grade' },
  guardianSection: { ur: 'سرپرست', en: 'Guardian' },
  guardianNameUr: { ur: 'سرپرست کا نام — اردو', en: 'Guardian name (Urdu)' },
  guardianNameEn: { ur: 'سرپرست کا نام — انگریزی', en: 'Guardian name (English)' },
  dateOfBirth: { ur: 'تاریخ پیدائش', en: 'Date of birth' },
  enrollmentDate: { ur: 'داخلہ کی تاریخ', en: 'Enrollment date' },
  exitDate: { ur: 'اخراج کی تاریخ', en: 'Exit date' },
  studentCountry: { ur: 'ملک', en: 'Country' },
  studentDistrictCurrent: { ur: 'موجودہ ضلع', en: 'Current district' },
  studentDistrictPermanent: { ur: 'مستقل ضلع', en: 'Permanent district' },
  studentAddressCurrent: { ur: 'موجودہ پتہ', en: 'Current address' },
  studentAddressPermanent: { ur: 'مستقل پتہ', en: 'Permanent address' },
  gender: { ur: 'جنس', en: 'Gender' },
  relationField: { ur: 'رشتہ', en: 'Relation' },
  profession: { ur: 'پیشہ', en: 'Profession' },
  guardianTableTitle: { ur: 'سرپرست', en: 'Guardians' },
  tabStudentBasic: { ur: 'بنیادی معلومات', en: 'Basic information' },
  tabStudentGuardian: { ur: 'سرپرست کی معلومات', en: 'Guardian information' },
  tabStudentPrevious: { ur: 'سابقہ مدارس', en: 'Previous schools' },
  tabStudentClass: { ur: 'موجودہ درجہ', en: 'Current class' },
  tabStudentLesson: { ur: 'سبق ٹریک', en: 'Lesson track' },
  studentFormTitleNew: { ur: 'نیا طالب علم شامل کریں', en: 'Add new student' },
  studentFormTitleEdit: { ur: 'طالب علم میں ترمیم', en: 'Edit student' },
  backToStudentList: { ur: 'واپس', en: 'Back' },
  classTypeField: { ur: 'کلاس کی قسم', en: 'Class type' },
  rollNumber: { ur: 'رول نمبر', en: 'Roll number' },
  rollNumberAutoBadge: { ur: 'خودکار', en: 'Auto' },
  rollNumberHint: {
    ur: 'کلاس منتخب کر کے محفوظ کرنے پر سسٹم رول نمبر بنائے گا۔',
    en: 'Choose a class and save — the system will assign the roll number.',
  },
  exitReasonField: { ur: 'اخراج کی وجہ', en: 'Reason for leaving' },
  previousSchoolYear: { ur: 'سال', en: 'Year' },
  previousSchoolGrade: { ur: 'درجہ', en: 'Class / grade' },
  previousSchoolInstitute: { ur: 'جامعہ / مدرسہ', en: 'Institute' },
  previousSchoolMarks: { ur: 'نمبرات', en: 'Marks' },
  previousSchoolResult: { ur: 'تقدیر / نتیجہ', en: 'Result' },
  lessonPara: { ur: 'سپارہ', en: 'Para (Juz)' },
  lessonStart: { ur: 'شروع', en: 'Start' },
  lessonComplete: { ur: 'مکمل', en: 'Complete' },
  teacherReadonly: { ur: 'استاد (کلاس کے مطابق)', en: 'Teacher (from class)' },
  photo: { ur: 'تصویر', en: 'Photo' },
  camera: { ur: 'کیمرہ', en: 'Camera' },
  capture: { ur: 'تصویر لیں', en: 'Capture' },

  // Tartibat
  sessionTitle: { ur: 'سیشن', en: 'Session' },
  sessionStart: { ur: 'شروع تاریخ', en: 'Start date' },
  sessionEnd: { ur: 'اختتام تاریخ', en: 'End date' },
  isActive: { ur: 'حالت', en: 'Status' },
  subjectName: { ur: 'شعبہ جات', en: 'Subajat' },
  subjectNameUr: { ur: 'شعبہ جات — اردو', en: 'Subajat (Urdu)' },
  subjectNameEn: { ur: 'شعبہ جات — انگریزی', en: 'Subajat (English)' },
  subjectSystemType: { ur: 'نظام / قسم', en: 'System / type' },
  subjectSystemTypeUr: { ur: 'نظام/قسم — اردو', en: 'System/type (Urdu)' },
  subjectSystemTypeEn: { ur: 'نظام/قسم — انگریزی', en: 'System/type (English)' },
  darjahName: { ur: 'درجہ', en: 'Darjah' },
  darjahNameUr: { ur: 'درجہ — اردو', en: 'Darjah (Urdu)' },
  darjahNameEn: { ur: 'درجہ — انگریزی', en: 'Darjah (English)' },
  examNameUr: { ur: 'امتحان کا نام', en: 'Exam name (Urdu)' },
  examNameEn: { ur: 'امتحان کا نام — انگریزی', en: 'Exam name (English)' },
  examTypeCustomUr: { ur: 'اپنی قسم — اردو', en: 'Custom type (Urdu)' },
  examTypeCustomEn: { ur: 'اپنی قسم — انگریزی', en: 'Custom type (English)' },
  darjahSubjects: { ur: 'شعبہ جات', en: 'Subajat' },
  bookTitle: { ur: 'کتاب', en: 'Book' },
  bookAuthor: { ur: 'مصنف', en: 'Author' },

  // Teachers
  teacherNameUr: { ur: 'استاد کا نام — اردو', en: 'Teacher name (Urdu)' },
  teacherNameEn: { ur: 'استاد کا نام — انگریزی', en: 'Teacher name (English)' },
  teacherParentage: { ur: 'نسب و ولدیت', en: 'Parentage / lineage' },
  teacherWalidiyat: { ur: 'ولدیت', en: 'Walidiyat / parentage' },
  parentageUr: { ur: 'نسب / ولدیت — اردو', en: 'Parentage (Urdu)' },
  parentageEn: { ur: 'نسب — انگریزی', en: 'Parentage (English)' },
  idCard: { ur: 'شناختی کارڈ', en: 'ID card' },
  status: { ur: 'حالت', en: 'Status' },
  maritalStatus: { ur: 'ازدواجی حیثیت', en: 'Marital status' },
  teacherCountry: { ur: 'ملک', en: 'Country' },
  teacherState: { ur: 'صوبہ / ریاست', en: 'State / province' },
  teacherCity: { ur: 'شہر', en: 'City' },
  teacherAddressCurrent: { ur: 'موجودہ پتہ', en: 'Current address' },
  teacherAddressPermanent: { ur: 'مستقل پتہ', en: 'Permanent address' },
  teacherDistrictCurrent: { ur: 'موجودہ ضلع', en: 'Current district' },
  teacherDistrictPermanent: { ur: 'مستقل ضلع', en: 'Permanent district' },
  deeniTaleem: { ur: 'دینی تعلیم', en: 'Religious education' },
  asriTaleem: { ur: 'عصری تعلیم', en: 'Secular education' },
  extraSkills: { ur: 'اضافی قابلیت', en: 'Additional skills' },
  jobStartDate: { ur: 'آغاز ملازمت', en: 'Job start' },
  jobEndDate: { ur: 'اختتام ملازمت', en: 'Job end' },

  // Grades
  year: { ur: 'سال', en: 'Year' },
  gradeNameUr: { ur: 'درجہ کا نام — اردو', en: 'Grade name (Urdu)' },
  gradeNameEn: { ur: 'درجہ کا نام — انگریزی', en: 'Grade name (English)' },
  gradeRowName: { ur: 'نام درجہ', en: 'Grade name' },
  totalGradesHint: { ur: 'کل درجات', en: 'Total grades' },
  section: { ur: 'سیکشن', en: 'Section' },
  code: { ur: 'کوڈ', en: 'Code' },
  responsibleTeacher: { ur: 'ذمہ دار استاد', en: 'Responsible teacher' },

  // Attendance
  date: { ur: 'تاریخ', en: 'Date' },
  period: { ur: 'پیریئڈ / وقت', en: 'Period' },
  teacher: { ur: 'استاد', en: 'Teacher' },
  attendancePresent: { ur: 'حاضر', en: 'Present' },
  attendanceAbsent: { ur: 'غائب', en: 'Absent' },
  attendanceSick: { ur: 'بیمار', en: 'Sick' },

  // Fees
  balance: { ur: 'بیلنس', en: 'Balance' },
  advance: { ur: 'ایڈوانس', en: 'Advance' },
  due: { ur: 'واجب', en: 'Due' },
  feeTitleUr: { ur: 'فیس عنوان — اردو', en: 'Fee title (Urdu)' },
  feeTitleEn: { ur: 'فیس عنوان — انگریزی', en: 'Fee title (English)' },
  feeStudentCol: { ur: 'طالب علم', en: 'Student' },
  feeBalancesHeading: { ur: 'بیلنس', en: 'Balances' },
  feeManagementHeading: { ur: 'فیس انتظام', en: 'Fee management' },
  feesCollectAction: { ur: 'وصولی', en: 'Collect' },
  amount: { ur: 'رقم', en: 'Amount' },

  // Inventory
  inventoryItemName: { ur: 'نام اشیاء', en: 'Item name' },
  inventoryCategory: { ur: 'کیٹیگری', en: 'Category' },
  inventoryUnitField: { ur: 'یونٹ', en: 'Unit' },
  inventoryQty: { ur: 'مقدار', en: 'Qty' },
  inventoryMovementKind: { ur: 'حرکت کی قسم', en: 'Movement type' },
  inventoryMovementReason: { ur: 'وجہ', en: 'Reason' },
  inventoryUnitPrice: { ur: 'فی یونٹ قیمت', en: 'Unit price' },
  inventoryLineValue: { ur: 'کل قیمت', en: 'Line total' },
  inventoryMinStock: { ur: 'کم اسٹاک حد', en: 'Low-stock threshold' },
  inventoryLocation: { ur: 'مقام / اسٹور', en: 'Location / store' },
  inventoryBarcode: { ur: 'بارکوڈ', en: 'Barcode' },
  inventoryPurchaseDate: { ur: 'خریداری کی تاریخ', en: 'Purchase date' },
  inventoryExpiryDate: { ur: 'میعاد ختم', en: 'Expiry date' },
  inventorySupplierUr: { ur: 'سپلائر — اردو', en: 'Supplier (Urdu)' },
  inventorySupplierEn: { ur: 'سپلائر — انگریزی', en: 'Supplier (English)' },
  inventoryUsageLocUr: { ur: 'استعمال کی جگہ — اردو', en: 'Usage location (Urdu)' },
  inventoryUsageLocEn: { ur: 'استعمال کی جگہ — انگریزی', en: 'Usage location (English)' },
  inventoryResponsibleUr: { ur: 'ذمہ دار — اردو', en: 'Responsible person (Urdu)' },
  inventoryResponsibleEn: { ur: 'ذمہ دار — انگریزی', en: 'Responsible person (English)' },
  inventoryMovementFlow: { ur: 'موومنٹ فلو', en: 'Movement flow' },
  inventoryDepartment: { ur: 'محکمہ', en: 'Department' },
  inventoryReferenceNo: { ur: 'حوالہ نمبر', en: 'Reference no.' },
  inventoryFromLocation: { ur: 'سے مقام', en: 'From location' },
  inventoryToLocation: { ur: 'مقام تک', en: 'To location' },
  inventoryLinkPurchaseExpense: { ur: 'خریداری پر خرچ (آمد و خرچ) درج کریں', en: 'Record purchase as finance expense' },
  inventoryPurchaseTotalCost: { ur: 'کل خریداری لاگت', en: 'Total purchase cost' },
  inventoryPurchaseExpenseCategory: { ur: 'خرچ کیٹیگری', en: 'Expense category' },
  inventoryPurchaseFundSource: { ur: 'فنڈ ماخذ', en: 'Fund source' },
  inventoryFinanceAccount: { ur: 'بیلنس اکاؤنٹ', en: 'Cash / account' },

  // Library (لائبریری رجسٹر)
  librarySerial: { ur: 'نمبر شمار', en: 'Serial #' },
  libraryBookTitle: { ur: 'نام کتاب', en: 'Book title' },
  libraryAuthor: { ur: 'مصنف / مؤلف', en: 'Author' },
  libraryVolumes: { ur: 'مجلدات', en: 'Volumes' },
  libraryShelf: { ur: 'رقم الخزانہ', en: 'Shelf / accession' },
  libraryLocation: { ur: 'مقام / محل وقوع', en: 'Location' },
  libraryLanguage: { ur: 'زبان', en: 'Language' },
  libraryPublisher: { ur: 'مطبع', en: 'Publisher' },
  libraryPublisherUr: { ur: 'مطبع — اردو', en: 'Publisher (Urdu)' },
  libraryPublisherEn: { ur: 'مطبع — انگریزی', en: 'Publisher (English)' },
  libraryEditor: { ur: 'محقق', en: 'Editor / researcher' },
  libraryEditorUr: { ur: 'محقق — اردو', en: 'Editor (Urdu)' },
  libraryEditorEn: { ur: 'محقق — انگریزی', en: 'Editor (English)' },
  libraryCondition: { ur: 'کیفیت', en: 'Condition' },
  libraryConditionUr: { ur: 'کیفیت — اردو', en: 'Condition (Urdu)' },
  libraryConditionEn: { ur: 'کیفیت — انگریزی', en: 'Condition (English)' },
  librarySubject: { ur: 'موضوع / فن', en: 'Subject / field' },
  libraryCopies: { ur: 'نقلیں', en: 'Copies' },
  libraryTotalCopies: { ur: 'کل نقلیں', en: 'Total copies' },
  libraryAvailableCopies: { ur: 'دستیاب نقلیں', en: 'Available copies' },
  libraryBorrower: { ur: 'لینے والا', en: 'Borrower' },
  libraryDueDate: { ur: 'واپسی کی تاریخ', en: 'Due date' },
  libraryIssueDate: { ur: 'اجراء کی تاریخ', en: 'Issue date' },
  libraryReturnDate: { ur: 'واپسی کی تاریخ', en: 'Return date' },

  speechTitle: { ur: 'تقریر کا عنوان', en: 'Speech title' },
  speechTitleUr: { ur: 'عنوان — اردو', en: 'Title (Urdu)' },
  speechTitleEn: { ur: 'عنوان — انگریزی', en: 'Title (English)' },
  speechSpeaker: { ur: 'مقرر', en: 'Speaker' },
  speechSpeakerUr: { ur: 'مقرر — اردو', en: 'Speaker (Urdu)' },
  speechSpeakerEn: { ur: 'مقرر — انگریزی', en: 'Speaker (English)' },
  speechSummary: { ur: 'خلاصہ', en: 'Summary' },
  speechSummaryUr: { ur: 'خلاصہ — اردو', en: 'Summary (Urdu)' },
  speechSummaryEn: { ur: 'خلاصہ — انگریزی', en: 'Summary (English)' },

  // Finance
  titleUr: { ur: 'عنوان — اردو', en: 'Title (Urdu)' },
  titleEn: { ur: 'عنوان — انگریزی', en: 'Title (English)' },
  txType: { ur: 'قسم (آمد / خرچ)', en: 'Type (income / expense)' },
  financeStatAccount: { ur: 'موجودہ رقم', en: 'Account balance' },
  financeStatNet: { ur: 'خالص', en: 'Net' },
  financeStatIncome: { ur: 'کل آمد', en: 'Total income' },
  financeStatExpense: { ur: 'کل خرچ', en: 'Total expenses' },
  transactionColTitle: { ur: 'عنوان', en: 'Title' },
  transactionColType: { ur: 'قسم', en: 'Type' },
  notes: { ur: 'نوٹس', en: 'Notes' },
  usageForUr: { ur: 'استعمال کہاں — اردو', en: 'Usage / where applied (Urdu)' },
  usageForEn: { ur: 'استعمال کہاں — انگریزی', en: 'Usage / where applied (English)' },

  // Settings / profile
  email: { ur: 'ای میل', en: 'Email' },
  addressUr: { ur: 'پتہ — اردو', en: 'Address (Urdu)' },
  addressEn: { ur: 'پتہ — انگریزی', en: 'Address (English)' },
  collegeUr: { ur: 'الجامعہ وابستگی — اردو', en: 'College affiliation (Urdu)' },
  collegeEn: { ur: 'الجامعہ وابستگی — انگریزی', en: 'College affiliation (English)' },
  bookTitleUr: { ur: 'کتاب کا عنوان — اردو', en: 'Book title (Urdu)' },
  bookTitleEn: { ur: 'کتاب کا عنوان — انگریزی', en: 'Book title (English)' },
  // Tartibat books
  bookAuthorUr: { ur: 'مصنف — اردو', en: 'Author (Urdu)' },
  bookAuthorEn: { ur: 'مصنف — انگریزی', en: 'Author (English)' },
  currentPassword: { ur: 'موجودہ پاس ورڈ', en: 'Current password' },
  newPassword: { ur: 'نیا پاس ورڈ', en: 'New password' },
  passwordSection: { ur: 'پاس ورڈ تبدیل کریں', en: 'Change password' },
}
