export const GUARDIAN_RELATIONS_STATIC = [
  { ur: 'والد', en: 'Father' },
  { ur: 'والدہ', en: 'Mother' },
  { ur: 'سرپرست', en: 'Guardian' },
  { ur: 'دادا', en: 'Grandfather (paternal)' },
  { ur: 'دادی', en: 'Grandmother (paternal)' },
  { ur: 'نانا', en: 'Grandfather (maternal)' },
  { ur: 'نانی', en: 'Grandmother (maternal)' },
  { ur: 'بھائی', en: 'Brother' },
  { ur: 'بہن', en: 'Sister' },
  { ur: 'بیٹا', en: 'Son' },
  { ur: 'بیٹی', en: 'Daughter' },
  { ur: 'چچا', en: 'Uncle (paternal)' },
  { ur: 'چچی', en: 'Aunt (paternal, by marriage)' },
  { ur: 'پھوپھا', en: 'Uncle (paternal aunt’s husband)' },
  { ur: 'پھوپھی', en: 'Aunt (paternal)' },
  { ur: 'ماموں', en: 'Uncle (maternal)' },
  { ur: 'ممانی', en: 'Aunt (maternal, by marriage)' },
  { ur: 'خالو', en: 'Uncle (maternal aunt’s husband)' },
  { ur: 'خالہ', en: 'Aunt (maternal)' },
  { ur: 'بھتیجا', en: 'Nephew (brother’s son)' },
  { ur: 'بھتیجی', en: 'Niece (brother’s daughter)' },
  { ur: 'بھانجا', en: 'Nephew (sister’s son)' },
  { ur: 'بھانجی', en: 'Niece (sister’s daughter)' },
  { ur: 'سسر', en: 'Father-in-law' },
  { ur: 'ساس', en: 'Mother-in-law' },
  { ur: 'شوہر', en: 'Husband' },
  { ur: 'بیوی', en: 'Wife' },
  { ur: 'سالہ', en: 'Brother-in-law (wife’s brother)' },
  { ur: 'سالی', en: 'Sister-in-law (wife’s sister)' },
  { ur: 'جیٹھ', en: 'Brother-in-law (husband’s elder brother)' },
  { ur: 'دیور', en: 'Brother-in-law (husband’s younger brother)' },
  { ur: 'نند', en: 'Sister-in-law (husband’s sister)' },
  { ur: 'بھابھی', en: 'Sister-in-law (brother’s wife)' },
  { ur: 'کزن', en: 'Cousin' },
  { ur: 'پڑوسی', en: 'Neighbor' },
  { ur: 'دوست', en: 'Friend' },
  { ur: 'استاد', en: 'Teacher' },
  { ur: 'مربی', en: 'Mentor' },
  { ur: 'سرپرست (غیر محرم)', en: 'Guardian (non-mahram)' },
]

