// Barrel: side-effect injects all domain endpoints, re-exports api + hooks
import './api/authUsersApi.js'
import './api/studentsApi.js'
import './api/teachersApi.js'
import './api/gradesApi.js'
import './api/attendanceApi.js'
import './api/feesApi.js'
import './api/financeApi.js'
import './api/inventoryApi.js'
import './api/libraryApi.js'
import './api/speechesApi.js'
import './api/idCardsApi.js'
import './api/studentActivitiesApi.js'
import './api/settingsApi.js'
import './api/tartibatApi.js'
import './api/timetableApi.js'
import './api/geoApi.js'
import './api/examsApi.js'
import './api/bookReadingApi.js'
import './api/recycleBinApi.js'

export { api } from './api/baseApi.js'

import { api } from './api/baseApi.js'

export const {
  useLoginMutation,
  useRegisterMutation,
  useRefreshTokenMutation,
  useLogoutSessionMutation,
  useForgotPasswordMutation,
  useResetPasswordMutation,
  useGetMeQuery,
  usePatchMeMutation,
  usePatchTenantMutation,
  useChangePasswordMutation,
  useGetUsersQuery,
  useCreateUserMutation,
  usePatchUserMutation,
  useDeleteUserMutation,
  useGetDashboardStatsQuery,
  useLazyGetSearchSuggestionsQuery,
  useGetStudentsQuery,
  useGetStudentQuery,
  useCreateStudentMutation,
  useUpdateStudentMutation,
  useDeleteStudentMutation,
  useUploadStudentPhotoMutation,
  useImportStudentsExcelMutation,
  useGetTeachersQuery,
  useGetTeacherQuery,
  useCreateTeacherMutation,
  useUpdateTeacherMutation,
  useDeleteTeacherMutation,
  useImportTeachersExcelMutation,
  useGetTeacherSalariesQuery,
  useGetTeacherSalaryPicklistQuery,
  useGetTeacherSalariesOverviewQuery,
  useCreateTeacherSalaryMutation,
  useUpdateTeacherSalaryMutation,
  useDeleteTeacherSalaryMutation,
  usePayTeacherSalarySlipMutation,
  useGetGradesQuery,
  useCreateGradeMutation,
  useUpdateGradeMutation,
  useDeleteGradeMutation,
  useGetStudentAttendanceQuery,
  useSaveStudentAttendanceMutation,
  useGetTeacherAttendanceQuery,
  useSaveTeacherAttendanceMutation,
  useGetAttendanceCategoriesQuery,
  useGetAttendanceSlotsQuery,
  useGetAttendanceRosterQuery,
  useGetAttendanceContextQuery,
  useGetAttendanceTimetableSlotsQuery,
  useGetStudentAttendanceReportQuery,
  useGetStudentAttendanceRecordsQuery,
  useGetAttendanceDaySummaryQuery,
  useGetTeacherAttendanceDaySummaryQuery,
  useGetTeacherAttendanceRecordsQuery,
  useGetTeacherAttendanceSummaryQuery,
  useGetFeeItemsQuery,
  useCreateFeeItemMutation,
  useUpdateFeeItemMutation,
  useDeleteFeeItemMutation,
  useGetFeeBalancesQuery,
  useGetStudentFeeBalanceQuery,
  useUpsertStudentFeeDueMutation,
  useApplyFeeItemMutation,
  useCollectFeeBalanceMutation,
  useApplyFeeMaafiMutation,
  useApplyFeeBalanceToDueMutation,
  useGetFeeAuditLogQuery,
  useDeleteFeeBalanceMutation,
  useGetFinanceOverviewQuery,
  useGetFinanceAccountsQuery,
  useGetTransactionsQuery,
  useCreateTransactionMutation,
  useUpdateTransactionMutation,
  useDeleteTransactionMutation,
  useGetInventoryStatsQuery,
  useGetInventoryItemsQuery,
  useCreateInventoryItemMutation,
  useUpdateInventoryItemMutation,
  useDeleteInventoryItemMutation,
  useGetInventoryMovementsQuery,
  useCreateInventoryMovementMutation,
  useGetSettingsQuery,
  usePatchSettingsMutation,
  useUploadTenantLogoMutation,
  useGetBooksQuery,
  useCreateBookMutation,
  useUpdateBookMutation,
  useDeleteBookMutation,
  useGetSessionsQuery,
  useGetSessionSummaryQuery,
  useCreateSessionMutation,
  useUpdateSessionMutation,
  useDeleteSessionMutation,
  useGetSubjectsQuery,
  useCreateSubjectMutation,
  useUpdateSubjectMutation,
  useDeleteSubjectMutation,
  useGetDarajatQuery,
  useCreateDarjahMutation,
  useUpdateDarjahMutation,
  useUpdateDarjahSubjectsMutation,
  useDeleteDarjahMutation,
  useGetSubjectBooksQuery,
  useCreateSubjectBookMutation,
  useUpdateSubjectBookMutation,
  useDeleteSubjectBookMutation,
  useGetTimeSlotsQuery,
  useCreateTimeSlotMutation,
  useUpdateTimeSlotMutation,
  useDeleteTimeSlotMutation,
  useGetTimetableEntriesQuery,
  useCreateTimetableEntryMutation,
  useUpdateTimetableEntryMutation,
  useDeleteTimetableEntryMutation,
  useGetGeoCountriesQuery,
  useGetGeoStatesQuery,
  useGetGeoCitiesQuery,
  useGetNextStudentIdQuery,
  useGetExamDashboardQuery,
  useGetExamResultMatrixQuery,
  useImportExamMarksMutation,
  useGetExamsQuery,
  useGetExamQuery,
  useCreateExamMutation,
  useUpdateExamMutation,
  useDeleteExamMutation,
  useGetExamClassesQuery,
  useAddExamClassesMutation,
  useRemoveExamClassMutation,
  useGetExamSubjectsQuery,
  useSaveExamSubjectsMutation,
  useDeleteExamSubjectMutation,
  useGetExamSnapshotQuery,
  useSaveExamRollNumbersMutation,
  useGenerateExamSnapshotMutation,
  useGetExamScheduleQuery,
  useSaveExamScheduleMutation,
  useDeleteExamScheduleMutation,
  useUpdateExamScheduleMutation,
  useGetExamAttendanceQuery,
  useSaveExamAttendanceMutation,
  useGetExamMarksQuery,
  useSaveExamMarksMutation,
  useApplyGraceMarksMutation,
  useUnlockExamMarksMutation,
  useProcessExamResultsMutation,
  useGetExamResultsQuery,
  usePublishExamResultsMutation,
  useGetExamAnalyticsQuery,
  useGetExamAuditLogQuery,
  useUnlockExamContainerMutation,
  useGetMyBooksWithProgressQuery,
  useGetBookWithReadingProgressQuery,
  useGetBookReadingRecordsQuery,
  useCreateBookReadingRecordMutation,
  useUpdateBookReadingRecordMutation,
  useDeleteBookReadingRecordMutation,
  useGetLibraryStatsQuery,
  useGetLibraryBooksQuery,
  useCreateLibraryBookMutation,
  useUpdateLibraryBookMutation,
  useDeleteLibraryBookMutation,
  useGetLibraryTransactionsQuery,
  useIssueLibraryBookMutation,
  useReturnLibraryBookMutation,
  useGetSpeechesQuery,
  useGetSpeechQuery,
  useCreateSpeechMutation,
  useUpdateSpeechMutation,
  useDeleteSpeechMutation,
  useGetIdCardTemplatesQuery,
  useGetIdCardStudentsQuery,
  useGenerateIdCardsMutation,
  useGetIdCardPrintPayloadQuery,
  useGetIdCardPrintHistoryQuery,
  useLogIdCardPrintMutation,
  useVerifyIdCardQuery,
  useGetActivityCategoriesQuery,
  useCreateActivityCategoryMutation,
  usePatchActivityCategoryMutation,
  useReorderActivityCategoriesMutation,
  useDeleteActivityCategoryMutation,
  useGetDailyActivitiesQuery,
  useBulkSaveDailyActivitiesMutation,
  useCopyDailyActivitiesMutation,
  useGetStudentActivityHistoryQuery,
  useGetActivityAnalyticsSummaryQuery,
  useGetRecycleBinQuery,
  useGetRecycleBinItemQuery,
  useRestoreRecycleItemMutation,
  useBulkRestoreRecycleMutation,
  usePermanentDeleteRecycleMutation,
  useBulkPermanentDeleteRecycleMutation,
} = api
